name: Deployment excersise
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@3
      - name: Install dependencies
        run: npm ci
      - name: Lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run buil
      - name: Deploy code
        run: echo "Deploying..."
          

















